### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by oh2th** [oh2th/fi.oh2th.alarmutils#10]
TypeError: Cannot read properties of undefined (reading 'start')
    at SchedulerDevice.schedulerEnable (/app/drivers/scheduler/device.js:211:18)
    at SchedulerDevice.onCapability_IS_ENABLED (/app/drivers/scheduler/device.js:299:23)
    at /app/lib/flows/actions.js:9:23
    at FlowCardAction._run (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCard.js:92:30)
    at ManagerFlow._onFlowCardRun (/node_modules/@athombv/homey-apps-sdk-v3/manager/flow.js:179:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by oh2th** [comment]
Someone has had a device without settings for the cron time. I think this is linked to https://github.com/oh2th/fi.oh2th.alarmutils/issues/9.
