### ISSUE TITLE
Cannot destructure property 'cronTime' of 'this.getSettingsCronTime(...)' as it is undefined

### ISSUE THREAD

**Issue by oh2th** [oh2th/fi.oh2th.alarmutils#9]
TypeError: Cannot destructure property 'cronTime' of 'this.getSettingsCronTime(...)' as it is undefined.
    at SchedulerDevice.restartCronJob (/app/drivers/scheduler/device.js:192:13)
    at SchedulerDevice.onAction_DEVICE_SCHEDULE_TIME (/app/drivers/scheduler/device.js:309:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/lib/flows/actions.js:14:5

**Comment by oh2th** [comment]
Action card without proper parameters?

**Comment by oh2th** [comment]
Needs input verification for the value given. Not an HP2023 issue and issue #10 is related to bad input.

**Comment by oh2th** [comment]
Stack traces caused by bad input include:

```
TypeError: Cannot destructure property 'cronTime' of 'this.getSettingsCronTime(...)' as it is undefined.
    at SchedulerDevice.restartCronJob (/app/drivers/scheduler/device.js:192:13)
    at SchedulerDevice.onAction_DEVICE_SCHEDULE_TIME (/app/drivers/scheduler/device.js:309:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/lib/flows/actions.js:14:5
```

```
TypeError: Cannot read properties of undefined (reading 'nextDates')
    at SchedulerDevice.getNextScheduledTime (/app/drivers/scheduler/device.js:232:32)
    at /app/app.js:86:51
    at Array.forEach (<anonymous>)
    at AlarmUtils.onAppInterval (/app/app.js:82:22)
    at CJ.onTick (/app/app.js:66:14)
    at CJ.fireOnTick (/app/node_modules/cron/lib/job.js:102:23)
    at Timeout.callbackWrapper [as _onTimeout] (/app/node_modules/cron/lib/job.js:174:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

```
TypeError: Cannot read properties of undefined (reading 'stop')
    at SchedulerDevice.schedulerDisable (/app/drivers/scheduler/device.js:221:18)
    at SchedulerDevice.onCapability_IS_ENABLED (/app/drivers/scheduler/device.js:300:15)
    at SchedulerDevice._onSetCapabilityValue (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
TypeError: Cannot read properties of undefined (reading 'start')
    at SchedulerDevice.schedulerEnable (/app/drivers/scheduler/device.js:211:18)
    at SchedulerDevice.onCapability_IS_ENABLED (/app/drivers/scheduler/device.js:299:23)
    at SchedulerDevice._onSetCapabilityValue (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```
```

**Comment by oh2th** [comment]
Root cause issue created.
